# Lo que debemos hacer:

- Distancia (tiempo) mínima(o) entre 2 puntos de una red.  Listo con el algoritmo de Dijkstra
- Incluir retraso por número de automoviles en una calle. Utilizando la función BPR
    - Paso intermedio función de avance de los automóviles.
- Incluir propiedades de agentes (paciencia, memoria, etc.). 
- Considerar inicios y destinos variados. 

## Algoritmo de Dijkstra

Se conocen todos los vértices de una red y sus aristas (incluidas las distancias). Se quiere saber cual es la "distancia mínima" entre dos vértices dados $x_i$ y $x_j$ de una red. 

El algoritmo es el siguiente: 

1. Se comienza poniendo la distancia a todos los vértices igual a $\infty$, excepto al mismo $x_i$. También se agregan rutas vacías en todos los vértices, excepto por el vértices $x_i$, donde se agrega la ruta $[x_i]$. Todos los vértices inicialmente están marcados como "no-visitados". 
- Se calcula la distancia a cada uno de los vecinos y se marca a $x_i$ como visitado. Las distancias se guardan como las distancias de $x_i$ a cada uno de esos vértices y las rutas se actualizas como $[x_i, x_{i_{n}}]$ donde $x_{i_{n}}$ es el vecino de $x_i$. 
- Se elige uno de los vecinos a alguno de los vértices visitados (el vértice visitado que tenga la menor distancia a $x_i$), y que no sea un vértice vicitado. Se cualcula la distancia a cada uno de sus vecinos y se estima con esto la distancia de $x_i$ a cada vertice vecino. Si la distancia calculada es menor que la que se tiene actualmente, se asigna esta nueva distancia y se actualiza la ruta como la ruta al vértice visitado agregando el vértice vecino. 
- Se marca como visitado al vértice elegido. Si la mínima distancia a los vecinos de los vértices visitados que no sean en sí vértices visitados es $\infty$, el programa regresa una ruta vacía y una distancia $\infty$ (significa que $x_i$ y $x_j$ están desconectados). Si $x_j$ está marcado como visitado, se regresa la distancia a $x_j$ y la ruta para llegar a $x_j$. 
- En cualquier otro caso, se repite el paso 3. 

In [1]:
∞ = Inf

Inf

In [2]:
function Dijkstra(x1, x2, Vecinos)
    ∞ = Inf
    #### PASO 1  ####
    n = length(Vecinos)
    Distancias_x1 = zeros(n)
    Distancias_NV = [[∞,i] for i in 1:n]
    Ruta = []
    Vertices_unv = [i for i in 1:n]
    if !(x2 in Vertices_unv)
        return ∞, []
    end
    for i in 1:n 
        if i ≠ Int(x1)
            Distancias_x1[i] = ∞
            push!(Ruta, [x1])
        else
            push!(Ruta, [x1])
        end
    end
    ### Termina PASO 1 ###
    ### PASO 2 ###
    x = Vecinos[x1]
    for i in 1:length(x[1])
        Distancias_x1[Int(x[1][i])] = x[2][i]
        Rutacopia = copy(Ruta[Int(x1)])
        push!(Rutacopia, x[1][i])
        Ruta[Int(x[1][i])] = copy(Rutacopia)
        Distancias_NV[Int(x[1][i])][1] = x[2][i]
    end   
    i = Int(findall(in(x1), Vertices_unv)[1])
    deleteat!(Vertices_unv, i)
    deleteat!(Distancias_NV, i)  
 #   filter!(e -> e ≠ x1, Vertices_unv)
    ### Termina PASO 2 ####
    while x2 in Vertices_unv
         ### PASO 3 ####
        k = argmin(Distancias_NV)
        j = Int(Distancias_NV[k][2])
        x = Vecinos[j]
        for i in 1:length(x[1])
            #    Distancias_x1[x[1][i]] = x[2][i]
            dist_xi_x1 = Distancias_NV[k][1]+x[2][i]
            
            if dist_xi_x1 < Distancias_x1[Int(x[1][i])]
                Distancias_x1[Int(x[1][i])] = dist_xi_x1
                Rutacopia = copy(Ruta[j])
                push!(Rutacopia, Int(x[1][i]))
                Ruta[Int(x[1][i])] = copy(Rutacopia)
                b = [algo[2] for algo in Distancias_NV]
                jj = findall(in(x[1][i]), b)  
                if length(jj)>0
                    Distancias_NV[Int(jj[1])][1] = dist_xi_x1
                end
            end     
        end   
        ### Termina PASO 3 ###
        ### PASO 4 ###
        i2 = findall(in(j), Vertices_unv)[1]
        deleteat!(Vertices_unv, i2)
        deleteat!(Distancias_NV, i2)  
        if length(Distancias_NV)>0
            i3 = argmin(Distancias_NV)
            dis = Distancias_NV[i3][1]
            if dis == ∞
                return ∞, []
            end
        end
        #### Termina paso 4 *Aunque continua abajo ####
        
        #### Paso 5 ####
    end  
    #### Paso 4 final ###
    return Distancias_x1[Int(x2)], Ruta[x2]
end    

Dijkstra (generic function with 1 method)

Pruebas con una red sencilla

In [3]:
#debemos agregar un arreglo más al final para escribir las distancias, 
#esto no debería afectar el algoritmo de Dijkstra
Vecinos = []
push!(Vecinos, [[2,3,4],[0.5,1,0.3],[1,2,2]])
push!(Vecinos, [[8,3,4],[1,0.8,.4],[1,2,2]])
push!(Vecinos, [[2,7,4],[0.8,3,1.5],[1,2,2]])
push!(Vecinos, [[2,3,6,5],[.4, 1.5, 3, 0.5],[1,2,2,3]])
push!(Vecinos, [[4,6],[0.5, 1.],[1,2]])
push!(Vecinos, [[4],[3.],[1]])
push!(Vecinos, [[3],[3.],[1]])
push!(Vecinos, [[2],[1.],[1]])

8-element Array{Any,1}:
 Array{Float64,1}[[2.0, 3.0, 4.0], [0.5, 1.0, 0.3], [1.0, 2.0, 2.0]]               
 Array{Float64,1}[[8.0, 3.0, 4.0], [1.0, 0.8, 0.4], [1.0, 2.0, 2.0]]               
 Array{Float64,1}[[2.0, 7.0, 4.0], [0.8, 3.0, 1.5], [1.0, 2.0, 2.0]]               
 Array{Float64,1}[[2.0, 3.0, 6.0, 5.0], [0.4, 1.5, 3.0, 0.5], [1.0, 2.0, 2.0, 3.0]]
 Array{Float64,1}[[4.0, 6.0], [0.5, 1.0], [1.0, 2.0]]                              
 Array{Float64,1}[[4.0], [3.0], [1.0]]                                             
 Array{Float64,1}[[3.0], [3.0], [1.0]]                                             
 Array{Float64,1}[[2.0], [1.0], [1.0]]                                             

In [4]:
#efectivamente no afecta
Dijkstra(1,7, Vecinos)

(4.0, [1, 3, 7])

Pruebas con una red aleatoria

In [5]:
L = 10000
Vecinos = []
for i in 1:L
    j = rand(1:7)
    conexiones = Int[]
    X = [k for k in 1:L if k ≠ i]
    for i in 1:j
        jj = rand(X)
        push!(conexiones, jj)
        filter!(e -> e ≠ jj, X)
    end
    push!(Vecinos,[conexiones, rand(j),rand(j)])
end

In [6]:
Vecinos

10000-element Array{Any,1}:
 Array{Float64,1}[[8415.0, 8529.0], [0.985013, 0.169131], [0.841182, 0.448438]]                                                                                                                                             
 Array{Float64,1}[[4600.0, 4717.0, 5397.0], [0.340418, 0.449324, 0.447137], [0.829254, 0.58977, 0.485362]]                                                                                                                  
 Array{Float64,1}[[7504.0], [0.739528], [0.748554]]                                                                                                                                                                         
 Array{Float64,1}[[2177.0, 6506.0, 7845.0], [0.0902145, 0.94802, 0.268215], [0.690627, 0.0763728, 0.405112]]                                                                                                                
 Array{Float64,1}[[9948.0, 565.0, 3076.0, 682.0, 8356.0, 1474.0, 5695.0], [0.364113, 0.6

In [7]:
@time Dijkstra(rand(1:L),rand(1:L), Vecinos)

  2.352913 seconds (511.34 k allocations: 723.473 MiB, 2.57% gc time)


(2.5326544728174634, [6492, 2503, 2237, 9203, 8875, 2212, 3339, 8576, 4931, 4961, 5687, 6612, 2231, 9416, 7397, 8134, 6206])

Función BPR, retraso asociado con otros automóviles en la misma calle

In [8]:
function BPR(tmin_ij, f_ij ,p_ij) # Funciona bien!! 
    α = 0.2 
    β = 10.
    t=tmin_ij *(1+α*(f_ij / p_ij)^β)
    return t
end

BPR (generic function with 1 method)

Evolución de los autos:
Los automóviles deben salir según su información de salida, de manera homogénea pero aleatoria en el transcurso de una hora.
¿Debería usar autos en arista o en los vértices?
¿A un auto le bloquean la calle los de adelante en la arista o todos los de la arista? ¿Cómo contamos los de adelante nada más (preservar el orden)?


Función para determinar las horas de salida de los autos, primero crearemos una serie de intervalos aleatorios y normalizaremos a una hora, para saber cuándo saldrá cada auto. La simulación termina cuando todos llegan a su destino.

In [9]:
#Para n número de autos generamos n valores aleatorios, 
#lo guardamos en un vector que luego normalizaremos a una hora

function Tiempos_Salida(n)
    TS=[]
    k=0.
    for i in 1:n
        j=rand()
        k+=j
        push!(TS,j)
    end
    TS=(1/k)*TS
    
    for i in 0:n-2
        l=0
        for j in 1:n-i
            l+=TS[j]
        end
        TS[n-i]=l
    end
    return TS
end
#Obtenemos una hora fraccionada en n pedazos, donde n es el número de autos

Tiempos_Salida (generic function with 1 method)

In [10]:
Tiempos_Salida(4)

4-element Array{Float64,1}:
 0.19449411172602446
 0.4521109661531274 
 0.5514010917801747 
 1.0                

Queremos saber qué ocurrirá primero
1. Un auto cambia de arista
2. Un auto parte de su origen
3. Un auto llega a su destino (que de hecho es parte del caso 1)

cada que una de esas cosas ocurra se avanzará un paso en el tiempo.

Necesitamos saber las distancias en las calles para saber cuánto tiempo tardarán en cambiar de arista los autos.
Y una forma de que cada auto recuerde el tiempo que le tomó atravesar cada arista. Ya sabemos cuánto tiempo le toma a los autos salir de su origen porque tenemos el vector donde están sus tiempos de salida.

In [11]:
#function evolucion_autos(Red, N, Planes_de_viaje)
#    T = zeros(N)
#    T2 = zeros(N)
#    X = [i for i in 1:N]
#    Lista_de_autos = []
#    while length(Planes_de_viaje)>0
#        δt = 2*rand()/N
#        if length(Lista_de_autos)>0
#            for j in 1:length(Lista_de_autos)
#                
#            end
#            
#        end
#        
#        i = rand(X)
#        filter!(e -> e ≠ i, X)
#       push!(Lista_de_autos, i)
#                
#    end 
#end

In [12]:
#El plan inicial de viaje de todos es el otorgado por el algoritmo de Dijkstra, cada auto necesita su pareja OD
function Planes_de_viaje(Red,pares_OD)
    PV=[]
    for i in 1:length(pares_OD)
        j,k=Dijkstra(pares_OD[i][1],pares_OD[i][2], Red)
        push!(k,0)
        push!(PV,k)
    end
    return PV
end

Planes_de_viaje (generic function with 1 method)

## Idea

Ir modificando la información en una copia de la red donde se ponga el promedio de lo que se han tardado los automóviles en cada arista para ir sacando nuevos planes de viaje con el algoritmo cada día.

In [14]:
#lo probamos para cierto número de autos con la red pequeña que hicimos y la pareja 1,7
Vecinos = []
push!(Vecinos, [[2,3,4],[0.5,1,0.3],[1,2,2]])
push!(Vecinos, [[8,3,4],[1,0.8,.4],[1,2,2]])
push!(Vecinos, [[2,7,4],[0.8,3,1.5],[1,2,2]])
push!(Vecinos, [[2,3,6,5],[.4, 1.5, 3, 0.5],[1,2,2,3]])
push!(Vecinos, [[4,6],[0.5, 1.],[1,2]])
push!(Vecinos, [[4],[3.],[1]])
push!(Vecinos, [[3],[3.],[1]])
push!(Vecinos, [[2],[1.],[1]])

pares_OD=[]
for i in 1:20
    push!(pares_OD,[1,7])
end
Planes_de_viaje(Vecinos,pares_OD)

20-element Array{Any,1}:
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]

Así que ya tenemos los planes de viaje de todos los autos y podemos obtener sus tiempos de salida.

In [15]:
#A cada auto le ponemos un vector de tiempos que irá rellenando conforme logre salir de cada arista
#le llamaremos TR, tiempos de recorrido, el vector de cada auto debe tener tantas 
#entradas como aristas tenga la red, al principio TR tendrá los tiempos mínimos reportados en las aristas de la red.
#function Genera_VT(N,Red)
#    t_orig=[]
#    for i in 1:length(Red)
#        for k in 1:length(Red[i][2])
#            push!(t_orig,Red[i][2][k])
#        end
#    end
#    TR=[]
#    for i in 1:N
#        push!(TR,t_orig)
#    end
#    return TR
#end

In [16]:
Genera_VT(3,Vecinos)

UndefVarError: UndefVarError: Genera_VT not defined

In [17]:
#A cada auto le ponemos un vector de tiempos que irá rellenando conforme logre salir de cada arista
#le llamaremos TR, tiempos de recorrido, el vector de cada auto debe tener tantas 
#entradas como aristas tenga la red, al principio TR tendrá los tiempos mínimos reportados en las aristas de la red.
function Genera_VT(N,Red)
    t_orig=[]
    for i in 1:length(Red)
        push!(t_orig,[Red[i][1],Red[i][2]])
    end
    TR=[]
    for i in 1:N
        push!(TR,t_orig)
    end
    return TR
end

Genera_VT (generic function with 1 method)

In [18]:
#Teorema del saludo de manos
#m=0
#    for i in 1:length(Vecinos)
#        m+=length(Vecinos[i][1])
#    end
#Int(m/2)

In [19]:
# idea para el siguiente bloque
TS=Tiempos_Salida(4)
t=.5
j=0
for i in 1:length(TS)
    j+=1
    if TS[i]-t > 0
        break
    end
end  
print(j,TS)

3[0.0632679, 0.245167, 0.586758, 1.0]

In [20]:
minimum([2,3,1,∞])

1.0

In [21]:
findall(in(3), [2,3,3,4])

2-element Array{Int64,1}:
 2
 3

In [42]:
#obtenemos qué tiempo sigue, una salida de un auto, o un cambio de arista
function sig_t(t,TS,Red,posiciones) #la función requiere saber en qué tiempo nos encontramos y los tiempos de salida de los autos.
    #calculamos el siguiente tiempo donde un auto saldrá, solamente si t<1.1 (es decir si ya pasó más de una
    #hora desde que la simulación comenzó)
    if t<1.1
        j=0
        for i in 1:length(TS)
            j+=1
            if TS[i]-t > 0
                break
            end
        end 
#el siguiente tiempo de salida y el auto que se moverá será 
        s_t_s=TS[j]
        auto_sale=j
    end
    
#ahora hay que calcular el siguiente tiempo de cambio de arista, dependerá de la función BPR 
# y de cuantos autos hay en cada arista. Creo que será mejor utilizar una función que calcule el BPR de todas las
# aristas donde sepamos que hay un automovil.
    
#Para obtener esto lo que debemos hacer es saber cuántos autos hay en cada arista, calcular la función BPR de
    # todas aquellas aristas en las que haya algún auto. Y finalmente calcular el tiempo restante que le tomará a
    #un auto en cada arista para llegar a la siguiente. Hagamos eso en una función aparte
    s_c_a_Todos=[]
    for k in 1:length(TS)
        p=posiciones[k]
        if (p[1] != 0) && (p[2] != 0)
            i=p[1]
            j=p[2]
            n=how_many_in(p,posiciones)
            j=findall(in(j),Red[i][1])[1]
            tmin_ij=Red[i][2][j]
            #f_ij debería ser el número de autos que hay contra el máximo que puede haber en esa calle.
            #para eso tenemos que tener información sobre el máximo de autos que caben ahí, 
            #eso lo pondremos como un cuarto arreglo en la red
            f_ij=n/(Red[i][4][j])
            p_ij=1.
            tiempo=BPR(tmin_ij, f_ij ,p_ij)
        else
            tiempo=∞
        end
        push!(s_c_a_Todos,tiempo)
    end   
    s_c_a=minimum(s_c_a_Todos)
    auto_cambia=findall(in(s_c_a),s_c_a_Todos)[1]
#finalmente se comparan estos dos tiempos para ver cuál será el próximo tiempo
    if s_t_s< s_c_a
        return s_t_s, auto_sale,"sale"
    else
        return s_c_a, auto_cambia,"cambia"
    end
end
    

sig_t (generic function with 1 method)

In [43]:
#posiciones es un array que nos indica la posición de los automóviles, al inicio la posición de todos es "[0,0]"
#luego esta posición se irá modificando a aristas (pares ordenados de vértices)

In [44]:
function how_many_in(p,posiciones)
    n=0
    i=p[1]
    j=p[2]
    for k in 1:length(posiciones)
        if posiciones[k]==[i,j]
            n+=1
        end
    end
    return n
end

how_many_in (generic function with 1 method)

In [50]:
function actualiza_posiciones!(posiciones,j,Planes_de_viaje,TR,t,accion)
    p=posiciones[j]
    i=p[1]
    k=p[2]
    r=findall(in(k),Planes_de_viaje[j])[1]
    
    if accion=="cambia"
        m=findall(in(k),TR[j][i][1])[1]
        TR[j][i][2][m]=t
        posiciones[j]=[k,Planes_de_viaje[j][r+1]]
    else 
        posiciones[j]=[Planes_de_viaje[j][1],Planes_de_viaje[j][2]]
    end
    return posiciones,TR
end

actualiza_posiciones! (generic function with 1 method)

In [51]:
function evolucion_autos(Red, Planes_de_viaje)
    #Llevaremos un contador del tiempo que ha ocurrido
    t=0.
    #Primero generamos los tiempos de salida
    n=length(Planes_de_viaje)
    TS=Tiempos_Salida(n)
    #vectores donde los autos irán registrando el tiempo que tarden en cada arista
    TR=Genera_VT(n,Red)
    posiciones=[]
    p_final=[]
    for i in 1:n
        push!(posiciones,[0,Planes_de_viaje[i][1]])
        l=length(Planes_de_viaje[i])
        push!(p_final,[Planes_de_viaje[i][l],0])
    end
    
    while posiciones != p_final
    #calculamos que ocurrirá después y en qué tiempo
        t,j,accion=sig_t(t,TS,Red,posiciones)
    #actualizamos las posiciones y TR
        posiciones,TR=actualiza_posiciones!(posiciones,j,Planes_de_viaje,TR,t,accion)
    end
    #ya que esté bien hecho solo hay que correr tiempos para los autos que NO han llegado.
    return TR 
end

evolucion_autos (generic function with 1 method)

In [52]:
#probamos en una red sencilla
Red = []
push!(Red, [[2,3,4],[0.5,1,0.3],[1,2,2],[8,15,7]])
push!(Red, [[8,3,4],[1,0.8,.4],[1,2,2],[20,14,2]])
push!(Red, [[2,7,4],[0.8,3,1.5],[1,2,2],[9,20,5]])
push!(Red, [[2,3,6,5],[.4, 1.5, 3, 0.5],[1,2,2,3],[1,2,3,4]])
push!(Red, [[4,6],[0.5, 1.],[1,2],[10,10]])
push!(Red, [[4],[3.],[1],[3]])
push!(Red, [[3],[3.],[1],[17]])
push!(Red, [[2],[1.],[1],[4]])

8-element Array{Any,1}:
 Array{Float64,1}[[2.0, 3.0, 4.0], [0.5, 1.0, 0.3], [1.0, 2.0, 2.0], [8.0, 15.0, 7.0]]                   
 Array{Float64,1}[[8.0, 3.0, 4.0], [1.0, 0.8, 0.4], [1.0, 2.0, 2.0], [20.0, 14.0, 2.0]]                  
 Array{Float64,1}[[2.0, 7.0, 4.0], [0.8, 3.0, 1.5], [1.0, 2.0, 2.0], [9.0, 20.0, 5.0]]                   
 Array{Float64,1}[[2.0, 3.0, 6.0, 5.0], [0.4, 1.5, 3.0, 0.5], [1.0, 2.0, 2.0, 3.0], [1.0, 2.0, 3.0, 4.0]]
 Array{Float64,1}[[4.0, 6.0], [0.5, 1.0], [1.0, 2.0], [10.0, 10.0]]                                      
 Array{Float64,1}[[4.0], [3.0], [1.0], [3.0]]                                                            
 Array{Float64,1}[[3.0], [3.0], [1.0], [17.0]]                                                           
 Array{Float64,1}[[2.0], [1.0], [1.0], [4.0]]                                                            

In [53]:
pares_OD=[]
for i in 1:20
    push!(pares_OD,[1,7])
end
PV=Planes_de_viaje(Red,pares_OD)

20-element Array{Any,1}:
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]
 [1, 3, 7, 0]

In [ ]:
evolucion_autos(Red,PV)